[build]
command = "sed -i \"s|DRUPAL_DOMAIN|${GATSBY_DRUPAL_ENDPOINT}|g\" netlify.toml && yarn build"

[[redirects]]
    from = "DRUPAL_DOMAIN/first-slug"
    to = "/"

[[redirects]]
    from = "DRUPAL_DOMAIN/first-slug"
    to = "/"